# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsRemote < Formula
  desc ""
  homepage "https://github.com/ronenniv/aws-remote"
  version "0.0.1-alpha"

  on_macos do
    url "https://github.com/ronenniv/aws-remote/releases/download/v0.0.1-alpha/aws-remote_0.0.1-alpha_darwin_all.tar.gz"
    sha256 "ddc9189f83a6cb1974ef0fe38106c396d060798f5e145e307671793271c35573"

    def install
      bin.install "aws-remote"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ronenniv/aws-remote/releases/download/v0.0.1-alpha/aws-remote_0.0.1-alpha_linux_arm64.tar.gz"
      sha256 "7e26e96729c9ce6135afa1fca1901c84d70bf55144ae7b75b2bfc7dd609e6866"

      def install
        bin.install "aws-remote"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ronenniv/aws-remote/releases/download/v0.0.1-alpha/aws-remote_0.0.1-alpha_linux_amd64.tar.gz"
      sha256 "641c1ee7f13fe1d249f427a4eb7dedbfb7113702f5bc71d116057226e6c9f747"

      def install
        bin.install "aws-remote"
      end
    end
  end
end
