# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsRemote < Formula
  desc ""
  homepage "https://github.com/ronenniv/aws-remote"
  version "0.0.1"

  on_macos do
    url "https://github.com/ronenniv/aws-remote/releases/download/v0.0.1/aws-remote_0.0.1_darwin_all.tar.gz"
    sha256 "22d066a08a64162d487fc49ebf596745d8fffea36402fee80d98f77fd2eb2a99"

    def install
      bin.install "aws-remote"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ronenniv/aws-remote/releases/download/v0.0.1/aws-remote_0.0.1_linux_arm64.tar.gz"
      sha256 "d7377a8595f7a770d2bbed57a6511b63181639c9f05d23e9fea5f5ac1dcfa381"

      def install
        bin.install "aws-remote"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ronenniv/aws-remote/releases/download/v0.0.1/aws-remote_0.0.1_linux_amd64.tar.gz"
      sha256 "737eb89bf494ea22c7395d546ef61699c85f91dbf138112c195da6cbfdfc1aed"

      def install
        bin.install "aws-remote"
      end
    end
  end
end
